[build.environment]
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
