/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/BarChart.vue')['default']
    BrandManagement: typeof import('./components/Brand/BrandManagement.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CategoryManagement: typeof import('./components/Category/CategoryManagement.vue')['default']
    CategoryStatics: typeof import('./components/Category/CategoryStatics.vue')['default']
    ColorManagement: typeof import('./components/Color/ColorManagement.vue')['default']
    CreateBrand: typeof import('./components/Brand/CreateBrand.vue')['default']
    CreateCategory: typeof import('./components/Category/CreateCategory.vue')['default']
    CreateColor: typeof import('./components/Color/CreateColor.vue')['default']
    CreateProduct: typeof import('./components/Products/CreateProduct.vue')['default']
    DashboardCard: typeof import('./components/DashboardCard.vue')['default']
    DonutChart: typeof import('./components/DonutChart.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    NUpload: typeof import('naive-ui')['NUpload']
    ProductsManagement: typeof import('./components/Products/ProductsManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
  }
}
