/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> }
    >
    '/Account/login': RouteRecordInfo<
      '/Account/login',
      '/Account/login',
      Record<never, never>,
      Record<never, never>
    >
    '/Brands/': RouteRecordInfo<
      '/Brands/',
      '/Brands',
      Record<never, never>,
      Record<never, never>
    >
    '/Categories/': RouteRecordInfo<
      '/Categories/',
      '/Categories',
      Record<never, never>,
      Record<never, never>
    >
    '/Colors/': RouteRecordInfo<
      '/Colors/',
      '/Colors',
      Record<never, never>,
      Record<never, never>
    >
    '/Comments/': RouteRecordInfo<
      '/Comments/',
      '/Comments',
      Record<never, never>,
      Record<never, never>
    >
    '/Customers/': RouteRecordInfo<
      '/Customers/',
      '/Customers',
      Record<never, never>,
      Record<never, never>
    >
    '/Invoices/': RouteRecordInfo<
      '/Invoices/',
      '/Invoices',
      Record<never, never>,
      Record<never, never>
    >
    '/News/': RouteRecordInfo<
      '/News/',
      '/News',
      Record<never, never>,
      Record<never, never>
    >
    '/Orders/': RouteRecordInfo<
      '/Orders/',
      '/Orders',
      Record<never, never>,
      Record<never, never>
    >
    '/Products/': RouteRecordInfo<
      '/Products/',
      '/Products',
      Record<never, never>,
      Record<never, never>
    >
    '/Products/Create': RouteRecordInfo<
      '/Products/Create',
      '/Products/Create',
      Record<never, never>,
      Record<never, never>
    >
    '/Reviews/': RouteRecordInfo<
      '/Reviews/',
      '/Reviews',
      Record<never, never>,
      Record<never, never>
    >
    '/Settings/': RouteRecordInfo<
      '/Settings/',
      '/Settings',
      Record<never, never>,
      Record<never, never>
    >
  }
}
